{{- if .Values.openshift.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: hedgedoc
  name: hedgedoc
spec:
  host: {{ .Values.hedgedoc.appname }}.2.{{ .Values.hedgedoc.domain }}
  port:
    targetPort: "3000"
  tls:
    insecureEdgeTerminationPolicy: {{ .Values.route.insecureEdgeTerminationPolicy }}
    termination: {{ .Values.route.termination }}
  to:
    kind: Service
    name: hedgedoc
    weight: 100
  wildcardPolicy: None
{{- end }}